### ISSUE TITLE
Root Page

### ISSUE THREAD

**Issue by josephhilby** [Consultancy-2208/west_fl_wx_fe#2]
“As a user, when I visit the root page I see the name of the application ‘West FL WX’, a link for New Users, and a link to Login.”
Subtasks:
- Set up route for root page (‘/’) to show method method in welcome controller (welcome#show)
- Set up show method in welcome controller
- Create the root page html.erb file
- Add Name and links to view page

**Comment by msakr21** [comment]
I will go ahead and close this issue since it was resolved in PR#1
