### ISSUE TITLE
User New Page

### ISSUE THREAD

**Issue by josephhilby** [Consultancy-2208/west_fl_wx_fe#3]
“As a user, when I visit the root page (‘/’) I click on New User link and I am taken to a create a new user form where I can fill in:
- first name, 
- last name, 
- email
- 4 checkboxes [^1]
  - Kids
  - Pets
  - Car
  - House
I can click the submit button.”
Subtasks:
- Set up route for new user form (‘/users/new’) to new method in users controller (users#new)
- Set up new method in users controller
- Create new user form html.erb file
- Add code for creating a form
- Add the code for the 4 text boxes and their respective labels
- Add the code for the 4 checkboxes and their respective labels

[^1]: Every user will have: Plan, Prep Kit, and Records (these will default to 'true' in the DB); the User will select one or multiple of [Kids, Pets, Car, House] (these will be false if not selected and true if selected).

**Comment by msakr21** [comment]
Currently this is complete with the exception of the password field due to the possibility of not needing it with OAuth. Will revisit when we start implementing OAuth.

**Comment by msakr21** [comment]
Removed password as requirement in issue as per our group and FE agreement with regards to OAuth implementation. This issue is now complete and closed as a result.
